---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: <your desired namespace> # this should be made in the same namespace where you are going to use the particular Token.
spec:
  provider: aws
  secretObjects:
  - secretName: api-token
    type: Opaque
    data: 
    - objectName: secret-token
      key: SECRET_TOKEN
  parameters:
    objects: |
      - objectName: prod/test/Mysql  
        objectType: secretsmanager
        objectAlias: secret-token

        # change the object name with the name of the secret manager name created in AWS account.