---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::617730884386:role/secrets-manager-role # arn of the secret-manager-role created.